#+TITLE: Project00 Key_Terms
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

NOTE: Be sure, when you are searching that they are logical defintions, that is
they are definitions that relate to math and Logic.

Example
* Superman Cannot be jumping really high
** identify
Superman is sometimes debated around his flying abilities
Some say that he is merely jumping and due to his speed and 
strength it appears to you and I that he is merely jumping and
moving his body to go up and down after that.
** Define
This is obviously false.  Superman is indeed levitating and not
Jumping
** Example/Explanation
If Superman were jumping when he catches Lois Lane she would be cut in half
due to the speed and trajectory of superman being the man of steel. This is because
he would have to slow/stop to the same speed as Lois to catch her and then "rejump".
He visually does not appear to be 'rejumping' and Lois isnt cut in half.  DONE!
** Non-Trivial Test question
What would be the best way to describe Superman's flight


a. He jumps and with his strength and speed is able to alter his path


b. He flys like a bird and flaps his wings


c. He levitates, he's an alien "HEELLLLLOOOO!"


d. Why do I care about Superman again, he's in the D.C. universe ... so dark and terrible movies!


**************** KEY TERMS ********************

* Contrapositive
When we switch the hypothesis and conclusion from a conditional statement and we negate both. It is in
the form if not q, then not p

EXAMPLE: We have the phrase -It is raining so I need an umbrella- if we put this phrase in its
contrapositive way it will be: If I dont need an umbrella, then it is not raining

NON-TRIVIAL QUESTION: 
  What is the logical way to put Contrapositive?
  a) p -> q
  b) ~q <- ~p
  c) ~q -> ~p
  c) ~p -> ~p

* Converse

A converse statement is when in the conditional statement, we change the hypothesis and the 
conclusion. Is in the form of if q, then p. 

EXAMPLE: If we have the phrase -It is raining so I need an umbrella-. In the Converse way It will be:
If I need and umbrella, then it rains

NON-TRIVIAL QUESTION:
  What is the logical way to put converse?
  a) q -> p
  b) p -> q
  c) ~p -> q
  d) p -> ~q

* inverse

Its when we negate the hypothesis and the conclusion but not changing the order of them.
Is in the form if not p, then not q

EXAMPLE: If we have the phrase -It is raining so I need an umbrella-. The inverse way it will be:
It is not raining then I dont need an umbrella

NON-TRIVIAL QUESTION
  What is the logical way to put inverse?
  a) q -> p
  b) p -> q
  c) ~q -> ~p
  d) ~p -> ~q

* R: real numbers

COMING SOON...

* Z: integers

Integer comes from the Latin word integer that means -whole-. An integer number is the one can be
written without a fractional component but as a whole. The set of integer numbers are composed of
zero, the natural numbers (positive integers) and their additive inverse (negative integers).
The Integer numbers are represented by the letter Z which it is the Zahlen symbol. Integer numbers
are part of the Real numbers

Some EXAMPLES of integer numbers are: 7, 0, 196, -201

NON-TRIVIAL QUESTION
  Which set of number are Integers?
  a) -1, 0, 3.2, 1/2
  b) 9/4 2, 19, 7
  c) 36, 81, 30, 79
  d) 5, 6.1, 4.3, 6.9

* Q: rational numbers



* predicate

* Domain

* CoDomain

* quantifier

* antecedent

* consequent

* Set

* Fallacy

* biconditional

* sufficient condition

* necessary condition

* ~p

* p ^ q

* p V q

* p XOR q

* p == q

* p -> q

* p <--> q

* Three dots in a triangle

* upside down A

* Backwards E

* union

* intersection

* Commutative laws

* associative laws

* distributive laws

* identity laws

* negation laws

* double negative law

* idempotent laws

* universal bound laws

* De morgan's laws

* absorption laws

* negations of t and c

* vacuously true

* Modus Ponens

* Modus Tollens

* Elimination: valid argument form

* Transitivity: Valid Argument form
