#+TITLE: Puzzles
#+LANGUAGE: en
#+OPTIONS: H:4 num:nil toc:nil \n:nil @:t ::t |:t ^:t *:t TeX:t LaTeX:t
#+OPTIONS: html-postamble:nil
#+STARTUP: showeverything entitiespretty

No help from me! Or brother Neff! Or any professor!
Other rando's ... sure.  Other students ... even bettar!

To get full "extra credit" you must fill out all four. 
Solutions and proofs are different.  Solving a puzzle like the bomb puzzle in a previous lab
is much different than proving it is impossible if we don't know if the bomb is heavier or lighter
with only 2 weights!

* Puzzles
** TODO TEU
  How many numbers between one and a million contain the digit 1 exactly once,
  and the sum of the rest of the digits is 16? Write elisp code with and without
  loops to verify your answer.
*** Rephrase
loop throught the numbers 1 to 1 million, and see if there is only one 1 and all the other number add up to 16
*** Approach
have 6 ints, when there is only one 1 add up the other numbers and see if that equals 16
*** Solution
#+BEGIN_SRC elisp :results output
(setq ones 0)
(setq tens 0)
(setq huns 0)
(setq thos 0)
(setq tenthos 0)
(setq hunthos 0)
(while ((not (= tens 9)) and ((not = ones 9)))
   (print (tens ones))
   (setq ones (1+ ones))
   (if (= ones 10)
      ((setq ones 0)
      (setq tens (1+ tens)))))
#+END_SRC
*** Proof
** TODO TME
  Sequences can be non-numeric as well. What is the pattern for this sequence?
: [m b w y me be wi yo met bew ith you meta bewi thyo uati metap bewit hyoua tirel]
  How long can it continue?
*** Rephrase
    This sequence isnot based on numbers, but letters. What is the sequence and
    how many more times until the sequence is over?
*** Approach
    We noticed the title of the textbook in this puzzle and I went from there to find any patterns
*** Solution
    Metaphors be with you a tireless work on play on words
    Metaphors bewithyou atireless workonpla
    Metaphorsbe withyouatir elessworkon playonwords
    
    11 times it can continue.
*** Proof

** TODO WRA
  Why is the sum of the reciprocals of the powers of two scaled by which power
  equal to two?
*** Rephrase
*** Approach
*** Solution
*** Proof
